Revert "task fin"
pjoterini/nerdboard_task pull request #3
Opened 2023-03-14 09:44 UTC by pjoterini

Reverts pjoterini/js-trainee-recruitment#2

2023-03-14 09:51 UTC, pjoterini commented
Instructions unclear, tried to merge it, because i thought just asking for the code review is part of the task, and you review it only after whole assingment is done. 😵‍💫

2023-03-21 14:18 UTC, Sumick commented
Can you please prepare PR with whole solution? Currently Im not able to properly do code review.

2023-03-21 15:26 UTC, pjoterini commented
I hope it is fine now. Sorry for trouble.

wt., 21 mar 2023 o 15:19 Jakub Wąsowski ***@***.***>
napisał(a):

> Can you please prepare PR with whole solution? Currently Im not able to
> properly do code review.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pjoterini/js-trainee-recruitment/pull/3#issuecomment-1477923613>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWX6T75QS2NZWPZQXA7IWYDW5G2FZANCNFSM6AAAAAAV2GFV5M>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-03-28 15:55 UTC, Sumick requested changes
These are quite important things to improve. This code has problems with maintainability, and possibility to scale. I noticed also one important thing regarding React performance (unmounted `onscroll` handler). More details below

2023-03-28 15:55 UTC, Sumick commented on src/components/SidebarMenu.tsx
> +        <a
**nitpick:** We should render these links using `map` to have greater control of code, and prevent copy & pasting

2023-03-28 15:55 UTC, Sumick commented on src/components/SidebarMenu.tsx
> +        <a ref={refs[1] as MutableRefObject<HTMLAnchorElement>} href="#cheetah">
**nitpick:** Casting types like this is a bad practice, as it can change in time, and you will don't know it - such implementation can crash your app

2023-03-28 15:55 UTC, Sumick commented on src/pages/index.tsx
> +  const ref7: MutableRefObject<HTMLElement | undefined> = useRef(undefined);
**nitpick:** This solution is not scalable, as it would be very hard to implement if you have 70 sections

2023-03-28 15:55 UTC, Sumick commented on src/pages/index.tsx
> +    window.onscroll = () => {
**issue:** You are not removing `onscroll` handler when unmounting component - it can cause memory leaks

2023-03-28 15:55 UTC, Sumick commented on src/pages/index.tsx
> +  // useEffect(() => {
**nitpick:** Redundant commented code

2023-03-28 16:26 UTC, pjoterini commented
Thank you for this review.  I hope you found some decent devs through the recruitment :)
Cheers

2023-04-02 08:04 UTC, closed without merging